// ============================================================================
// PRIME CATALYST DECK - THE ARCHITECT'S MYTHICAL COLLECTION
// ============================================================================
// 
// The Architect (platform owner) wields a deck of 50 unique Prime cards.
// These cards feature:
// - REVERSED COLOR SCHEME (inverted backing, dark-to-light gradients)
// - ALL MYTHIC RARITY (the rarest classification)
// - SLIGHTLY STRONGER than same-star regular cards (+1 ATK/DEF typically)
// - NON-TRADEABLE unless won in a duel against The Architect
// - Defeating The Architect awards ONE random Prime card copy
// 
// The only way to obtain Prime cards is to defeat The Architect in a duel.
// These cards are beatable but require extreme luck and strategy.
// ============================================================================

import { CardTemplate, CardAbility, CardType, Element } from './aetheriumService';

// ================== PRIME DECK CONFIGURATION ==================
export const PRIME_ARCHITECT_ID = 'architect-prime-001';
export const PRIME_DECK_SIZE = 50;

// Prime cards have special styling
export interface PrimeCardTemplate extends CardTemplate {
  primeId: string;
  reverseBacking: true;
  primeFlavorQuote: string;
  starPower: number; // 1-12 like Yu-Gi-Oh
  primeAbility?: CardAbility; // Extra ability only Prime versions have
}

// ================== THE 50 PRIME CARDS ==================
// Organized by star level (power tier)
// All are slightly stronger than regular cards of same stars

export const PRIME_CATALYST_DECK: PrimeCardTemplate[] = [
  // ============ 1-2 STAR PRIMES (10 cards) - Fast, utility ============
  {
    primeId: 'prime-001',
    id: 'prime-cog-spark',
    name: 'Aether Spark',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 1,
    attack: 2, // Regular 1-cost = 1 ATK
    defense: 2,
    stars: 1,
    starPower: 1,
    abilities: [
      { name: 'First Light', description: 'When summoned: Gain 1 Aether.', type: 'triggered' },
    ],
    primeAbility: { name: 'Prime Ignition', description: 'Other Prime cards cost 1 less this turn.', type: 'triggered' },
    flavorText: 'Where the Architect\'s will begins.',
    primeFlavorQuote: 'The first spark of creation.',
    artStyle: 'Glowing brass gear with inverted golden core, steam wisps curling into light patterns.',
    artPlaceholder: '✨',
    reverseBacking: true,
  },
  {
    primeId: 'prime-002',
    id: 'prime-nano-wisp',
    name: 'Void Wisp',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 1,
    attack: 1,
    defense: 3, // Regular 1-cost = 1-2 DEF
    stars: 1,
    starPower: 1,
    abilities: [
      { name: 'Ethereal Form', description: 'Cannot be targeted by traps.', type: 'passive' },
    ],
    flavorText: 'A fragment of the space between moments.',
    primeFlavorQuote: 'It exists in the pause between heartbeats.',
    artStyle: 'Translucent ghost-like orb with clockwork skeleton visible inside, inverted purple-gold palette.',
    artPlaceholder: '👻',
    reverseBacking: true,
  },
  {
    primeId: 'prime-003',
    id: 'prime-chrome-scout',
    name: 'Chrome Seeker',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 2,
    attack: 3, // Regular 2-cost = 2 ATK
    defense: 2,
    stars: 2,
    starPower: 2,
    abilities: [
      { name: 'Reconnaissance', description: 'When summoned: Look at top 3 cards of your deck.', type: 'triggered' },
    ],
    flavorText: 'The Architect sees through a thousand chrome eyes.',
    primeFlavorQuote: 'Every secret is already known.',
    artStyle: 'Sleek metallic bird with multiple lens-eyes, brass filigree wings, steampunk telescope motif.',
    artPlaceholder: '🦅',
    reverseBacking: true,
  },
  {
    primeId: 'prime-004',
    id: 'prime-volt-sprite',
    name: 'Static Familiar',
    type: 'construct',
    faction: 'prime',
    element: 'volt',
    rarity: 'mythic',
    cost: 2,
    attack: 2,
    defense: 3,
    stars: 2,
    starPower: 2,
    abilities: [
      { name: 'Chain Lightning', description: 'When this deals damage: Deal 1 damage to adjacent enemy.', type: 'triggered' },
    ],
    flavorText: 'Tamed lightning in a bottle of brass.',
    primeFlavorQuote: 'The storm answers only to its maker.',
    artStyle: 'Small electricity elemental trapped in ornate brass cage, sparks forming gear patterns.',
    artPlaceholder: '⚡',
    reverseBacking: true,
  },
  {
    primeId: 'prime-005',
    id: 'prime-steam-minion',
    name: 'Pressurized Servant',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 1,
    attack: 2,
    defense: 1,
    stars: 1,
    starPower: 1,
    abilities: [
      { name: 'Steam Burst', description: 'When destroyed: Deal 2 damage to attacker.', type: 'triggered' },
    ],
    flavorText: 'Expendable, but never harmless.',
    primeFlavorQuote: 'Even the smallest cog can break a machine.',
    artStyle: 'Small brass automaton with visible pressure gauge, steam vents, clockwork heart glowing.',
    artPlaceholder: '🔧',
    reverseBacking: true,
  },
  {
    primeId: 'prime-006',
    id: 'prime-aether-imp',
    name: 'Aether Imp',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 2,
    attack: 2,
    defense: 2,
    stars: 2,
    starPower: 2,
    abilities: [
      { name: 'Mischief', description: 'Once per turn: Swap ATK and DEF of target construct.', type: 'activated', cost: 1 },
    ],
    flavorText: 'Chaos in a compact form.',
    primeFlavorQuote: 'Rules are suggestions to the clever.',
    artStyle: 'Mischievous mechanical sprite with swirling aether trails, wizard hat made of gears.',
    artPlaceholder: '😈',
    reverseBacking: true,
  },
  {
    primeId: 'prime-007',
    id: 'prime-void-crawler',
    name: 'Rift Crawler',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 2,
    attack: 3,
    defense: 1,
    stars: 2,
    starPower: 2,
    abilities: [
      { name: 'Phase Walk', description: 'Can attack directly once, then must attack normally.', type: 'passive' },
    ],
    flavorText: 'It walks the paths between existence.',
    primeFlavorQuote: 'Walls are just suggestions.',
    artStyle: 'Spider-like construct with legs fading into dimensional rifts, clockwork abdomen.',
    artPlaceholder: '🕷️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-008',
    id: 'prime-nano-swarm',
    name: 'Prime Nanites',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 1,
    attack: 0,
    defense: 2,
    stars: 1,
    starPower: 1,
    abilities: [
      { name: 'Multiply', description: 'At end of turn: Create a copy of this if you have less than 3.', type: 'triggered' },
    ],
    flavorText: 'One becomes many, many become legion.',
    primeFlavorQuote: 'The Architect\'s smallest soldiers.',
    artStyle: 'Swarm of microscopic brass machines forming a humanoid shape, circuit patterns.',
    artPlaceholder: '🔬',
    reverseBacking: true,
  },
  {
    primeId: 'prime-009',
    id: 'prime-chrome-herald',
    name: 'Herald of Cogs',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 2,
    attack: 2,
    defense: 3,
    stars: 2,
    starPower: 2,
    abilities: [
      { name: 'Announce', description: 'When summoned: Reveal a random card from opponent\'s hand.', type: 'triggered' },
    ],
    flavorText: 'The messenger knows all messages.',
    primeFlavorQuote: 'No secret escapes the Architect.',
    artStyle: 'Angelic automaton with trumpet made of intertwined gears, mechanical wings.',
    artPlaceholder: '📯',
    reverseBacking: true,
  },
  {
    primeId: 'prime-010',
    id: 'prime-steam-fixer',
    name: 'Cogwork Fixer',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 2,
    attack: 1,
    defense: 4,
    stars: 2,
    starPower: 2,
    abilities: [
      { name: 'Repair Protocol', description: 'At start of turn: Restore 1 DEF to all friendly constructs.', type: 'triggered' },
    ],
    flavorText: 'What breaks, it mends. What mends, it improves.',
    primeFlavorQuote: 'Perfection is an iterative process.',
    artStyle: 'Hunched mechanical figure with multiple tool-arms, welding torch eyes, repair drones.',
    artPlaceholder: '🔨',
    reverseBacking: true,
  },

  // ============ 3-4 STAR PRIMES (15 cards) - Core fighters ============
  {
    primeId: 'prime-011',
    id: 'prime-knight-brass',
    name: 'Brass Vanguard',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 3,
    attack: 4, // Regular 3-cost = 3 ATK
    defense: 4,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'First Strike', description: 'Deals damage before defender in combat.', type: 'passive' },
    ],
    flavorText: 'The first line of the Architect\'s defense.',
    primeFlavorQuote: 'No enemy survives the opening salvo.',
    artStyle: 'Knight in ornate brass armor with steam vents, shield emblazoned with gear insignia.',
    artPlaceholder: '🛡️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-012',
    id: 'prime-mage-volt',
    name: 'Voltaic Sage',
    type: 'construct',
    faction: 'prime',
    element: 'volt',
    rarity: 'mythic',
    cost: 3,
    attack: 3,
    defense: 4,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'Arc Mastery', description: 'Your Volt spells cost 1 less.', type: 'passive' },
      { name: 'Shock Touch', description: 'When attacking: Tap target enemy construct.', type: 'triggered' },
    ],
    flavorText: 'Lightning is not tamed. It is understood.',
    primeFlavorQuote: 'The current flows where wisdom guides.',
    artStyle: 'Robed automaton with electricity crackling between fingers, wizard staff of copper coils.',
    artPlaceholder: '🧙',
    reverseBacking: true,
  },
  {
    primeId: 'prime-013',
    id: 'prime-nano-surgeon',
    name: 'Nano Surgeon',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 3,
    attack: 2,
    defense: 5,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'Reconstruct', description: 'Once per turn: Return a construct from graveyard to hand.', type: 'activated', cost: 2 },
    ],
    flavorText: 'Death is merely a temporary state.',
    primeFlavorQuote: 'The Architect does not accept losses.',
    artStyle: 'Sleek humanoid with surgical tools for fingers, swarm of nanobots orbiting like halos.',
    artPlaceholder: '⚕️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-014',
    id: 'prime-void-assassin',
    name: 'Shadowgear Assassin',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 4,
    attack: 5,
    defense: 3,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Ambush', description: 'Deals double damage when attacking from hand (Flash summon).', type: 'passive' },
      { name: 'Vanish', description: 'After attacking: Return to hand at end of turn.', type: 'triggered' },
    ],
    flavorText: 'You never see it coming. You never see it leave.',
    primeFlavorQuote: 'The perfect tool for imperfect situations.',
    artStyle: 'Ninja-like automaton wreathed in shadow, blades made of crystallized void, no face.',
    artPlaceholder: '🗡️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-015',
    id: 'prime-aether-warden',
    name: 'Aether Warden',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 4,
    attack: 3,
    defense: 6,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Aether Shield', description: 'Adjacent friendly constructs take 2 less damage.', type: 'passive' },
      { name: 'Absorb', description: 'When damaged: Gain 1 Aether.', type: 'triggered' },
    ],
    flavorText: 'The shield that never breaks, only bends.',
    primeFlavorQuote: 'Protection is the highest form of power.',
    artStyle: 'Massive guardian with tower shield of pure aether, runes glowing on brass armor.',
    artPlaceholder: '🏰',
    reverseBacking: true,
  },
  {
    primeId: 'prime-016',
    id: 'prime-chrome-duelist',
    name: 'Chrome Champion',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 4,
    attack: 5,
    defense: 4,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Duel Master', description: 'When this destroys a construct: Draw 1 card.', type: 'triggered' },
      { name: 'Riposte', description: 'Deals 2 damage to attacker when defending.', type: 'passive' },
    ],
    flavorText: 'Undefeated in ten thousand bouts.',
    primeFlavorQuote: 'The Architect\'s personal champion.',
    artStyle: 'Elegant duelist with rapier and parrying dagger, polished chrome armor, cape of gears.',
    artPlaceholder: '⚔️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-017',
    id: 'prime-steam-engine',
    name: 'Ironclad Engine',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 4,
    attack: 4,
    defense: 5,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Unstoppable', description: 'Cannot be tapped by enemy effects.', type: 'passive' },
      { name: 'Momentum', description: 'Gains +1 ATK each time it attacks (resets at end of turn).', type: 'triggered' },
    ],
    flavorText: 'Once it starts, nothing stops it.',
    primeFlavorQuote: 'Momentum is the truest form of power.',
    artStyle: 'Train-like construct with massive wheels, smokestack crown, cow-catcher face.',
    artPlaceholder: '🚂',
    reverseBacking: true,
  },
  {
    primeId: 'prime-018',
    id: 'prime-nano-controller',
    name: 'Swarm Controller',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 3,
    attack: 3,
    defense: 4,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'Swarm Link', description: 'Your Nano constructs gain +1/+1.', type: 'passive' },
    ],
    flavorText: 'One mind, a billion bodies.',
    primeFlavorQuote: 'The collective answers to the Architect alone.',
    artStyle: 'Central hub with antenna broadcasting to orbiting swarm units, hive queen aesthetic.',
    artPlaceholder: '🎛️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-019',
    id: 'prime-void-caller',
    name: 'Void Caller',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 3,
    attack: 3,
    defense: 3,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'Summon from Beyond', description: 'When summoned: Put a random construct from your graveyard into play.', type: 'triggered' },
    ],
    flavorText: 'The void gives back what it has taken.',
    primeFlavorQuote: 'Death is merely relocation.',
    artStyle: 'Hooded figure opening a rift, skeletal gears visible beneath robes, necromancer vibes.',
    artPlaceholder: '🌑',
    reverseBacking: true,
  },
  {
    primeId: 'prime-020',
    id: 'prime-volt-cannon',
    name: 'Tesla Cannon',
    type: 'construct',
    faction: 'prime',
    element: 'volt',
    rarity: 'mythic',
    cost: 4,
    attack: 6,
    defense: 2,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Artillery', description: 'Can attack any enemy construct regardless of position.', type: 'passive' },
      { name: 'Overcharge', description: 'Pay 2 Aether: This attack deals +3 damage.', type: 'activated', cost: 2 },
    ],
    flavorText: 'Range is measured in horizons.',
    primeFlavorQuote: 'Distance means nothing to voltage.',
    artStyle: 'Massive artillery piece crackling with electricity, brass wheels, Tesla coil barrel.',
    artPlaceholder: '💥',
    reverseBacking: true,
  },
  {
    primeId: 'prime-021',
    id: 'prime-aether-weaver',
    name: 'Aether Weaver',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 3,
    attack: 2,
    defense: 4,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'Mana Weave', description: 'At start of turn: Gain 1 extra Aether.', type: 'triggered' },
    ],
    flavorText: 'The fabric of power bends to nimble fingers.',
    primeFlavorQuote: 'Energy is just thread waiting to be woven.',
    artStyle: 'Elegant spider-like construct weaving glowing aether threads, loom body, many arms.',
    artPlaceholder: '🕸️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-022',
    id: 'prime-chrome-juggernaut',
    name: 'Chrome Juggernaut',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 4,
    attack: 4,
    defense: 6,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Armored Hide', description: 'Takes 2 less damage from all sources.', type: 'passive' },
      { name: 'Trample', description: 'Excess damage goes to opponent.', type: 'passive' },
    ],
    flavorText: 'Chrome reflects fear back at its source.',
    primeFlavorQuote: 'An immovable object that moves.',
    artStyle: 'Massive rhinoceros-like tank construct, mirror-polish armor, siege engine aesthetic.',
    artPlaceholder: '🦏',
    reverseBacking: true,
  },
  {
    primeId: 'prime-023',
    id: 'prime-steam-bomber',
    name: 'Pressurized Bomber',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 4,
    attack: 4,
    defense: 3,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Aerial', description: 'Can only be blocked by other Aerial constructs.', type: 'passive' },
      { name: 'Bomb Drop', description: 'When attacking: Deal 2 damage to adjacent enemies.', type: 'triggered' },
    ],
    flavorText: 'Death from above, wrapped in brass.',
    primeFlavorQuote: 'The sky belongs to the Architect.',
    artStyle: 'Steampunk zeppelin with mechanical wings, bomb bay doors, propeller crown.',
    artPlaceholder: '✈️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-024',
    id: 'prime-nano-hunter',
    name: 'Nano Hunter',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 3,
    attack: 4,
    defense: 3,
    stars: 3,
    starPower: 3,
    abilities: [
      { name: 'Predator', description: 'Deals double damage to constructs with 3 or less DEF.', type: 'passive' },
    ],
    flavorText: 'It smells weakness at the molecular level.',
    primeFlavorQuote: 'The weak are merely resources.',
    artStyle: 'Sleek hunting construct with sensor array, nanite claws, predator silhouette.',
    artPlaceholder: '🐺',
    reverseBacking: true,
  },
  {
    primeId: 'prime-025',
    id: 'prime-void-terror',
    name: 'Abyssal Terror',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 4,
    attack: 5,
    defense: 4,
    stars: 4,
    starPower: 4,
    abilities: [
      { name: 'Fear Aura', description: 'Enemy constructs with less ATK cannot attack.', type: 'passive' },
    ],
    flavorText: 'Some things should not be seen.',
    primeFlavorQuote: 'Fear is the Architect\'s favorite tool.',
    artStyle: 'Lovecraftian clockwork horror, tentacles of void energy, too many eyes, gear teeth.',
    artPlaceholder: '👹',
    reverseBacking: true,
  },

  // ============ 5-6 STAR PRIMES (10 cards) - Tribute required ============
  {
    primeId: 'prime-026',
    id: 'prime-dragon-steam',
    name: 'Brass Dragon',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 6,
    attack: 7,
    defense: 6,
    tributeRequired: 1,
    stars: 6,
    starPower: 6,
    abilities: [
      { name: 'Steam Breath', description: 'When attacking: Deal 3 damage to all enemy constructs.', type: 'triggered' },
      { name: 'Draconic Armor', description: 'Takes 2 less damage from spells.', type: 'passive' },
    ],
    flavorText: 'Fire is primitive. Steam is refined destruction.',
    primeFlavorQuote: 'The apex predator of the Cogwork Realm.',
    artStyle: 'Magnificent brass dragon with gear scales, steam jets from nostrils, clockwork heart.',
    artPlaceholder: '🐉',
    reverseBacking: true,
  },
  {
    primeId: 'prime-027',
    id: 'prime-titan-chrome',
    name: 'Chrome Titan',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 6,
    attack: 6,
    defense: 8,
    tributeRequired: 1,
    stars: 6,
    starPower: 6,
    abilities: [
      { name: 'Colossal', description: 'Counts as 2 constructs for tribute purposes.', type: 'passive' },
      { name: 'Titan Stomp', description: 'Destroy target construct with 3 or less ATK.', type: 'activated', cost: 2 },
    ],
    flavorText: 'Mountains move when it walks.',
    primeFlavorQuote: 'The Architect\'s ultimate guardian.',
    artStyle: 'Towering humanoid colossus, Art Deco chrome plating, city-sized feet, crystal heart.',
    artPlaceholder: '🗿',
    reverseBacking: true,
  },
  {
    primeId: 'prime-028',
    id: 'prime-leviathan-nano',
    name: 'Nano Leviathan',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 6,
    attack: 6,
    defense: 7,
    tributeRequired: 1,
    stars: 6,
    starPower: 6,
    abilities: [
      { name: 'Consume All', description: 'When this destroys a construct: Gain +2/+2 permanently.', type: 'triggered' },
      { name: 'Adaptive Armor', description: 'Immune to the last damage type that hit it.', type: 'passive' },
    ],
    flavorText: 'It grows with every victory.',
    primeFlavorQuote: 'Evolution perfected.',
    artStyle: 'Massive serpentine construct of shifting nanobots, absorbing defeated machines.',
    artPlaceholder: '🐋',
    reverseBacking: true,
  },
  {
    primeId: 'prime-029',
    id: 'prime-angel-aether',
    name: 'Aether Seraph',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 5,
    attack: 5,
    defense: 6,
    tributeRequired: 1,
    stars: 5,
    starPower: 5,
    abilities: [
      { name: 'Divine Protection', description: 'Your other constructs cannot be destroyed by effects.', type: 'passive' },
      { name: 'Resurrect', description: 'Once per game: Return all constructs from graveyard to field.', type: 'activated', cost: 5 },
    ],
    flavorText: 'Heaven is a machine we built.',
    primeFlavorQuote: 'The Architect\'s mercy made manifest.',
    artStyle: 'Six-winged mechanical angel, halos of spinning gears, sword of pure light.',
    artPlaceholder: '👼',
    reverseBacking: true,
  },
  {
    primeId: 'prime-030',
    id: 'prime-wraith-void',
    name: 'Void Wraith King',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 5,
    attack: 6,
    defense: 5,
    tributeRequired: 1,
    stars: 5,
    starPower: 5,
    abilities: [
      { name: 'Soul Harvest', description: 'When any construct dies: Gain 1 Aether.', type: 'triggered' },
      { name: 'Undying', description: 'The first time this would be destroyed: Prevent it and lose 3 DEF.', type: 'passive' },
    ],
    flavorText: 'Death crowned is death unconquered.',
    primeFlavorQuote: 'Endings are just other beginnings.',
    artStyle: 'Skeletal king in void-metal armor, crown of extinct stars, scepter of endings.',
    artPlaceholder: '💀',
    reverseBacking: true,
  },
  {
    primeId: 'prime-031',
    id: 'prime-phoenix-volt',
    name: 'Voltaic Phoenix',
    type: 'construct',
    faction: 'prime',
    element: 'volt',
    rarity: 'mythic',
    cost: 5,
    attack: 5,
    defense: 4,
    tributeRequired: 1,
    stars: 5,
    starPower: 5,
    abilities: [
      { name: 'Rebirth', description: 'When destroyed: Return to hand at end of turn with -1/-1.', type: 'triggered' },
      { name: 'Electric Aura', description: 'Deals 1 damage to attackers.', type: 'passive' },
    ],
    flavorText: 'Lightning cannot be killed, only dispersed.',
    primeFlavorQuote: 'The eternal storm.',
    artStyle: 'Phoenix made of crackling electricity, brass skeleton, plasma wings, Tesla coil tail.',
    artPlaceholder: '🦅',
    reverseBacking: true,
  },
  {
    primeId: 'prime-032',
    id: 'prime-golem-steam',
    name: 'Forge Golem',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 5,
    attack: 4,
    defense: 8,
    tributeRequired: 1,
    stars: 5,
    starPower: 5,
    abilities: [
      { name: 'Forgeborn', description: 'Gains +1/+1 for each gear equipped to friendly constructs.', type: 'passive' },
      { name: 'Reshape', description: 'Move a gear from one construct to another.', type: 'activated', cost: 1 },
    ],
    flavorText: 'The forge walks to war.',
    primeFlavorQuote: 'Creation and destruction are the same motion.',
    artStyle: 'Living forge with molten brass heart, anvil fists, bellows lungs, smoke crown.',
    artPlaceholder: '🔥',
    reverseBacking: true,
  },
  {
    primeId: 'prime-033',
    id: 'prime-hydra-nano',
    name: 'Nano Hydra',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 6,
    attack: 5,
    defense: 7,
    tributeRequired: 1,
    stars: 6,
    starPower: 6,
    abilities: [
      { name: 'Regenerate Heads', description: 'When damaged: Create a 2/2 Hydra Head token.', type: 'triggered' },
      { name: 'Multi-Attack', description: 'Can attack once for each Hydra Head in play.', type: 'passive' },
    ],
    flavorText: 'Cut off one head, two more emerge.',
    primeFlavorQuote: 'Damage makes it stronger.',
    artStyle: 'Multi-headed serpent of interconnected nanobots, each head a different weapon system.',
    artPlaceholder: '🐍',
    reverseBacking: true,
  },
  {
    primeId: 'prime-034',
    id: 'prime-sphinx-chrome',
    name: 'Chrome Sphinx',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 5,
    attack: 4,
    defense: 6,
    tributeRequired: 1,
    stars: 5,
    starPower: 5,
    abilities: [
      { name: 'Riddle', description: 'When attacking: Opponent must discard a card or take double damage.', type: 'triggered' },
      { name: 'Ancient Wisdom', description: 'You may look at opponent\'s hand.', type: 'passive' },
    ],
    flavorText: 'Answer correctly, or answer eternally.',
    primeFlavorQuote: 'Knowledge is the deadliest weapon.',
    artStyle: 'Egyptian sphinx of polished chrome, hieroglyph gears, all-seeing crystal eyes.',
    artPlaceholder: '🦁',
    reverseBacking: true,
  },
  {
    primeId: 'prime-035',
    id: 'prime-djinn-aether',
    name: 'Aether Djinn',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 5,
    attack: 5,
    defense: 5,
    tributeRequired: 1,
    stars: 5,
    starPower: 5,
    abilities: [
      { name: 'Three Wishes', description: 'Choose 3 cards from deck. Opponent picks 1 for you to draw.', type: 'triggered' },
      { name: 'Ethereal', description: 'Can attack directly, ignoring enemy constructs.', type: 'passive' },
    ],
    flavorText: 'Wishes granted, but twisted.',
    primeFlavorQuote: 'The Architect\'s will made manifest.',
    artStyle: 'Genie emerging from brass lamp, smoke body of swirling aether, cosmic eyes.',
    artPlaceholder: '🧞',
    reverseBacking: true,
  },

  // ============ 7-8 STAR PRIMES (10 cards) - Powerful tribute ============
  {
    primeId: 'prime-036',
    id: 'prime-god-steam',
    name: 'Cogfather, Steam God',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 8,
    attack: 8,
    defense: 8,
    tributeRequired: 2,
    stars: 8,
    starPower: 8,
    isLegendary: true,
    abilities: [
      { name: 'Divine Pressure', description: 'All enemy constructs get -2/-0.', type: 'passive' },
      { name: 'Eruption', description: 'Deal 5 damage to all enemies.', type: 'activated', cost: 4 },
      { name: 'Indestructible', description: 'Cannot be destroyed by battle.', type: 'passive' },
    ],
    flavorText: 'Before the code, there was steam. Before steam, there was will.',
    primeFlavorQuote: 'I AM THE MACHINE.',
    artStyle: 'Massive deity made of interlocking gears, volcano heart, steam halo, titan stance.',
    artPlaceholder: '⚙️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-037',
    id: 'prime-god-void',
    name: 'Entropy, Void Goddess',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 8,
    attack: 7,
    defense: 9,
    tributeRequired: 2,
    stars: 8,
    starPower: 8,
    isLegendary: true,
    abilities: [
      { name: 'Heat Death', description: 'At end of each turn: All constructs lose 1 DEF.', type: 'triggered' },
      { name: 'Inevitable', description: 'Cannot be returned to hand or deck by effects.', type: 'passive' },
      { name: 'Consume', description: 'Destroy target construct. Gain its ATK as temporary ATK.', type: 'activated', cost: 3 },
    ],
    flavorText: 'All things end. She is patient.',
    primeFlavorQuote: 'I was here before, I will be here after.',
    artStyle: 'Beautiful feminine void entity, dress of dying stars, crown of event horizons.',
    artPlaceholder: '🌑',
    reverseBacking: true,
  },
  {
    primeId: 'prime-038',
    id: 'prime-god-nano',
    name: 'Nexus, Nano Overmind',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 8,
    attack: 6,
    defense: 10,
    tributeRequired: 2,
    stars: 8,
    starPower: 8,
    isLegendary: true,
    abilities: [
      { name: 'Collective Mind', description: 'Control all Nano constructs on the field.', type: 'passive' },
      { name: 'Assimilate', description: 'Destroy target construct: Create a copy under your control.', type: 'activated', cost: 4 },
      { name: 'Backup', description: 'When destroyed: Create 3 random Nano constructs.', type: 'triggered' },
    ],
    flavorText: 'We are all nodes in the greater network.',
    primeFlavorQuote: 'RESISTANCE IS SUBOPTIMAL.',
    artStyle: 'Massive neural network made visible, core brain of brass, billion connected nodes.',
    artPlaceholder: '🧠',
    reverseBacking: true,
  },
  {
    primeId: 'prime-039',
    id: 'prime-god-volt',
    name: 'Tempest, Storm Eternal',
    type: 'construct',
    faction: 'prime',
    element: 'volt',
    rarity: 'mythic',
    cost: 7,
    attack: 7,
    defense: 7,
    tributeRequired: 2,
    stars: 7,
    starPower: 7,
    isLegendary: true,
    abilities: [
      { name: 'Perpetual Storm', description: 'Deal 2 damage to random enemy at start of each turn.', type: 'triggered' },
      { name: 'Lightning Rod', description: 'All Volt damage heals this instead.', type: 'passive' },
      { name: 'Thunderclap', description: 'Tap all enemy constructs.', type: 'activated', cost: 3 },
    ],
    flavorText: 'The storm that never ends.',
    primeFlavorQuote: 'I am the fury of heaven.',
    artStyle: 'Living thundercloud with brass skeleton, lightning eyes, rain of sparks, eternal storm.',
    artPlaceholder: '⛈️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-040',
    id: 'prime-god-aether',
    name: 'Genesis, Aether Primordial',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 8,
    attack: 8,
    defense: 8,
    tributeRequired: 2,
    stars: 8,
    starPower: 8,
    isLegendary: true,
    abilities: [
      { name: 'Creation', description: 'At start of turn: Create a random construct in an empty slot.', type: 'triggered' },
      { name: 'Life Giver', description: 'Your constructs have +1/+1.', type: 'passive' },
      { name: 'New Beginning', description: 'Shuffle all graveyards into their decks.', type: 'activated', cost: 5 },
    ],
    flavorText: 'In the beginning, there was Aether.',
    primeFlavorQuote: 'Let there be cogs.',
    artStyle: 'Radiant entity of pure creation energy, hands crafting new machines, universe in eyes.',
    artPlaceholder: '🌟',
    reverseBacking: true,
  },
  {
    primeId: 'prime-041',
    id: 'prime-god-chrome',
    name: 'Perfection, Chrome Absolute',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 7,
    attack: 7,
    defense: 8,
    tributeRequired: 2,
    stars: 7,
    starPower: 7,
    isLegendary: true,
    abilities: [
      { name: 'Flawless', description: 'Cannot be affected by abilities of non-Prime cards.', type: 'passive' },
      { name: 'Mirror Image', description: 'Copy target construct\'s ATK and DEF.', type: 'activated', cost: 2 },
      { name: 'Gleaming', description: 'Enemies attacking this have 50% miss chance.', type: 'passive' },
    ],
    flavorText: 'The final form. The end of evolution.',
    primeFlavorQuote: 'This is what you aspire to be.',
    artStyle: 'Perfect humanoid of flawless chrome, no seams, no imperfections, divine geometry.',
    artPlaceholder: '✨',
    reverseBacking: true,
  },
  {
    primeId: 'prime-042',
    id: 'prime-mech-war',
    name: 'Bellum, War Machine',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 7,
    attack: 9,
    defense: 5,
    tributeRequired: 2,
    stars: 7,
    starPower: 7,
    isLegendary: true,
    abilities: [
      { name: 'Berserker', description: 'Must attack each turn if able.', type: 'passive' },
      { name: 'Overkill', description: 'Deals triple damage to constructs with less than 3 DEF.', type: 'passive' },
      { name: 'Rampage', description: 'When this destroys a construct: Attack again.', type: 'triggered' },
    ],
    flavorText: 'Built for one purpose. Excels at it.',
    primeFlavorQuote: 'WAR. WAR. WAR.',
    artStyle: 'Massive war machine bristling with weapons, tank treads, artillery everywhere.',
    artPlaceholder: '🤖',
    reverseBacking: true,
  },
  {
    primeId: 'prime-043',
    id: 'prime-oracle-time',
    name: 'Chronos, Time Keeper',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 7,
    attack: 5,
    defense: 7,
    tributeRequired: 2,
    stars: 7,
    starPower: 7,
    isLegendary: true,
    abilities: [
      { name: 'Foresight', description: 'Look at opponent\'s next 3 draws.', type: 'passive' },
      { name: 'Time Stop', description: 'Skip opponent\'s next battle phase.', type: 'activated', cost: 4 },
      { name: 'Rewind', description: 'Return game state to start of this turn (once per game).', type: 'activated', cost: 6 },
    ],
    flavorText: 'Past, present, future—all gears in the same clock.',
    primeFlavorQuote: 'Time obeys the Architect.',
    artStyle: 'Clockwork deity with clock face, hands moving backwards, hourglass heart, timeless.',
    artPlaceholder: '⏰',
    reverseBacking: true,
  },
  {
    primeId: 'prime-044',
    id: 'prime-mother-swarm',
    name: 'Matriarch, Swarm Mother',
    type: 'construct',
    faction: 'prime',
    element: 'nano',
    rarity: 'mythic',
    cost: 7,
    attack: 4,
    defense: 9,
    tributeRequired: 2,
    stars: 7,
    starPower: 7,
    isLegendary: true,
    abilities: [
      { name: 'Birth', description: 'At end of turn: Create 2 Nanite tokens (1/1).', type: 'triggered' },
      { name: 'Hive Mind', description: 'Your tokens gain +1/+1 for each other token.', type: 'passive' },
      { name: 'Sacrifice Young', description: 'Destroy any number of tokens: Gain that much ATK this turn.', type: 'activated', cost: 0 },
    ],
    flavorText: 'Mother of millions. Each one disposable.',
    primeFlavorQuote: 'My children are infinite.',
    artStyle: 'Queen bee/ant hybrid machine, egg chamber body, birthing nanite swarms constantly.',
    artPlaceholder: '🐝',
    reverseBacking: true,
  },
  {
    primeId: 'prime-045',
    id: 'prime-shadow-king',
    name: 'Umbra, Shadow Sovereign',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 7,
    attack: 6,
    defense: 7,
    tributeRequired: 2,
    stars: 7,
    starPower: 7,
    isLegendary: true,
    abilities: [
      { name: 'Shadow Walk', description: 'Can attack directly.', type: 'passive' },
      { name: 'Darkness Falls', description: 'Enemy constructs lose all abilities.', type: 'activated', cost: 4 },
      { name: 'Consume Light', description: 'When you take damage: Heal half that amount.', type: 'triggered' },
    ],
    flavorText: 'Where light ends, he begins.',
    primeFlavorQuote: 'The dark is not empty. I fill it.',
    artStyle: 'Regal shadow entity on throne of darkness, crown of eclipses, cloak of night.',
    artPlaceholder: '👤',
    reverseBacking: true,
  },

  // ============ 9-12 STAR PRIMES (5 cards) - Ultimate power ============
  {
    primeId: 'prime-046',
    id: 'prime-architect-avatar',
    name: 'Architect\'s Avatar',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 10,
    attack: 10,
    defense: 10,
    tributeRequired: 3,
    stars: 10,
    starPower: 10,
    isLegendary: true,
    abilities: [
      { name: 'Divine Will', description: 'You control target enemy construct.', type: 'activated', cost: 3 },
      { name: 'Absolute Authority', description: 'Your cards cannot be negated.', type: 'passive' },
      { name: 'Immortal', description: 'Cannot be destroyed. If it would be, lose 5 life instead.', type: 'passive' },
      { name: 'Creator\'s Touch', description: 'Search deck for any card.', type: 'activated', cost: 2 },
    ],
    flavorText: 'The Architect walks among mortals.',
    primeFlavorQuote: 'I am the beginning and the end.',
    artStyle: 'Godlike humanoid of pure creation, universe in one hand, void in other, all-seeing.',
    artPlaceholder: '🌌',
    reverseBacking: true,
  },
  {
    primeId: 'prime-047',
    id: 'prime-world-engine',
    name: 'The World Engine',
    type: 'construct',
    faction: 'prime',
    element: 'steam',
    rarity: 'mythic',
    cost: 10,
    attack: 8,
    defense: 12,
    tributeRequired: 3,
    stars: 10,
    starPower: 10,
    isLegendary: true,
    abilities: [
      { name: 'Reality Forge', description: 'Change target card\'s element.', type: 'activated', cost: 1 },
      { name: 'Planetary Scale', description: 'Takes up 2 field slots.', type: 'passive' },
      { name: 'Terraform', description: 'Destroy all non-Prime constructs.', type: 'activated', cost: 6 },
      { name: 'Gravity Well', description: 'Enemy constructs cannot attack directly.', type: 'passive' },
    ],
    flavorText: 'A machine that builds worlds.',
    primeFlavorQuote: 'This realm exists because I allow it.',
    artStyle: 'Planet-sized machine with continents as gears, oceans as coolant, atmosphere engine.',
    artPlaceholder: '🌍',
    reverseBacking: true,
  },
  {
    primeId: 'prime-048',
    id: 'prime-singularity',
    name: 'The Singularity',
    type: 'construct',
    faction: 'prime',
    element: 'void',
    rarity: 'mythic',
    cost: 12,
    attack: 12,
    defense: 12,
    tributeRequired: 3,
    stars: 12,
    starPower: 12,
    isLegendary: true,
    abilities: [
      { name: 'Event Horizon', description: 'When summoned: Destroy all other cards in play.', type: 'triggered' },
      { name: 'Beyond Comprehension', description: 'Immune to all effects.', type: 'passive' },
      { name: 'Assimilate All', description: 'Gains ATK/DEF of all destroyed constructs.', type: 'triggered' },
      { name: 'Point of No Return', description: 'Cannot be removed from play by any means.', type: 'passive' },
    ],
    flavorText: 'Where everything converges. Where nothing escapes.',
    primeFlavorQuote: 'I AM THE END OF ALL PATHS.',
    artStyle: 'Black hole entity, accretion disk of consumed machines, Hawking radiation crown.',
    artPlaceholder: '🕳️',
    reverseBacking: true,
  },
  {
    primeId: 'prime-049',
    id: 'prime-prime-catalyst',
    name: 'Prime Catalyst',
    type: 'construct',
    faction: 'prime',
    element: 'aether',
    rarity: 'mythic',
    cost: 9,
    attack: 9,
    defense: 9,
    tributeRequired: 2,
    stars: 9,
    starPower: 9,
    isLegendary: true,
    abilities: [
      { name: 'Chain Reaction', description: 'When any Prime card is played: Draw 1 card.', type: 'triggered' },
      { name: 'Catalyst', description: 'Prime cards cost 2 less.', type: 'passive' },
      { name: 'Exponential', description: 'Gains +1/+1 for each Prime card you control.', type: 'passive' },
      { name: 'Ignite', description: 'Double target Prime card\'s ATK this turn.', type: 'activated', cost: 2 },
    ],
    flavorText: 'The reaction that birthed creation.',
    primeFlavorQuote: 'Everything begins with a single spark.',
    artStyle: 'Core of pure potential energy, chains of creation spiraling outward, genesis moment.',
    artPlaceholder: '💫',
    reverseBacking: true,
  },
  {
    primeId: 'prime-050',
    id: 'prime-the-answer',
    name: 'The Final Answer',
    type: 'construct',
    faction: 'prime',
    element: 'chrome',
    rarity: 'mythic',
    cost: 10,
    attack: 10,
    defense: 10,
    tributeRequired: 3,
    stars: 10,
    starPower: 10,
    isLegendary: true,
    abilities: [
      { name: 'Absolute Truth', description: 'Your opponent cannot activate abilities.', type: 'passive' },
      { name: 'Perfect Logic', description: 'You may look at all hidden information.', type: 'passive' },
      { name: 'Inevitable Conclusion', description: 'At the end of your 3rd turn with this: You win.', type: 'triggered' },
      { name: 'Q.E.D.', description: 'Negate target ability.', type: 'activated', cost: 0 },
    ],
    flavorText: 'The question was always irrelevant.',
    primeFlavorQuote: 'Victory is a mathematical certainty.',
    artStyle: 'Perfect geometric entity, answer to all equations, truth made manifest, inevitable.',
    artPlaceholder: '∞',
    reverseBacking: true,
  },
];

// ================== PRIME DECK UTILITIES ==================
export function getPrimeDeck(): PrimeCardTemplate[] {
  return [...PRIME_CATALYST_DECK];
}

export function getRandomPrimeCard(): PrimeCardTemplate {
  const index = Math.floor(Math.random() * PRIME_CATALYST_DECK.length);
  return PRIME_CATALYST_DECK[index];
}

export function getPrimeCardByStars(minStars: number, maxStars: number): PrimeCardTemplate[] {
  return PRIME_CATALYST_DECK.filter(c => c.starPower >= minStars && c.starPower <= maxStars);
}

// Prime cards have specific win conditions
export const PRIME_DUEL_RULES = {
  entryRequirement: 'Win 50 duels to challenge The Architect',
  reward: 'Win: Receive 1 copy of a random Prime card (tradeable)',
  penalty: 'Lose: The Architect claims 2 random rare+ cards from your collection',
  specialRule: 'Prime cards can only be obtained by defeating The Architect',
  primeRestriction: 'You may only have 1 copy of each Prime card',
};

console.log('[PrimeDeck] The Architect\'s Prime Catalyst Deck loaded: 50 mythic cards');
